
library(tidyverse)
library(glue)

fld_struct <- read_file("src/read-rdi.c") %>%
  str_match("typedef struct \\{([^\\}]+)\\}\\s*rdi_fixed_leader_data_t") %>%
  .[, 2] %>%
  str_replace_all("//.*?\n", "\n") %>%
  read_lines() %>%
  str_subset("[^\\s]+")

vld_struct <- read_file("src/read-rdi.c") %>%
  str_match("typedef struct \\{([^\\}]+)\\}\\s*rdi_variable_leader_data_t") %>%
  .[, 2] %>%
  str_replace_all("//.*?\n", "\n") %>%
  read_lines() %>%
  str_subset("[^\\s]+")

rdi_item_struct <- c(fld_struct, vld_struct) %>%
  str_match("([A-Za-z0-9_]+)\\s+([A-Za-z0-9_]+)(\\[[0-9]+\\])?") %>%
  .[, 2:4] %>%
  as.data.frame() %>%
  setNames(c("c_type", "c_name", "c_size")) %>%
  mutate(
    type = c(rep("fixed", length(fld_struct)), rep("variable", length(vld_struct))),
    c_index = seq_len(n()) - 1,
    c_size = parse_number(c_size),
    r_c_type = case_when(
      !is.na(c_size) ~ "VECSXP",
      c_type == "uint16_scaled_by_100_t" ~ "REALSXP",
      TRUE ~ "INTSXP"
    ),
    r_c_create = glue(
      "SET_VECTOR_ELT(items_df, { c_index }, Rf_allocVector({ r_c_type }, n_data_types));"
    ),
    r_c_set = case_when(
      r_c_type == "VECSXP" ~
        glue(
          "
            SEXP r_{ c_name } = PROTECT(Rf_allocVector(INTSXP, { c_size }));
            for (int j = 0; j < { c_size }; j++) {{
                INTEGER(r_{ c_name })[j] = { type }.{ c_name }[j];
            }}
            SET_VECTOR_ELT(VECTOR_ELT(items_df, { c_index }),  i, r_{ c_name });
            UNPROTECT(1);
            "
        ),
      r_c_type == "REALSXP" & c_type == "uint16_scaled_by_100_t" ~ glue(
        "REAL(VECTOR_ELT(items_df, { c_index }))[i] = { type }.{ c_name } / 100.0;"
      ),
      TRUE ~ glue(
        "INTEGER(VECTOR_ELT(items_df, { c_index }))[i] = { type }.{ c_name };"
      )
    )
  )


alloc_items_df <- glue("
SEXP rdi_alloc_items_df(R_xlen_t n_data_types) {{
    const char* items_df_names[] = {{ { paste0('\"', rdi_item_struct$c_name , '\"', collapse = ', ') }  , \"\"}};
    SEXP items_df = PROTECT(Rf_mkNamed(VECSXP, items_df_names));
{ paste0('    ', rdi_item_struct$r_c_create, collapse = '\n') }
    UNPROTECT(1);
    return items_df;
}}
")


set_items_df <- glue("
void rdi_add_fixed_to_items(SEXP items_df, R_xlen_t i, rdi_fixed_leader_data_t fixed) {{
{ paste0('    ', rdi_item_struct$r_c_set[rdi_item_struct$type == 'fixed'], collapse = '\n')}

}}

void rdi_add_variable_to_items(SEXP items_df, R_xlen_t i, rdi_variable_leader_data_t variable) {{
{ paste0('    ', rdi_item_struct$r_c_set[rdi_item_struct$type == 'variable'], collapse = '\n')}
}}
")

final_include <- glue("
// end generated by data-raw/read-rdi-tools.R

{ alloc_items_df }

{ set_items_df }

// end generated by data-raw/read-rdi-tools.R
")

write_file(final_include, "src/rdi-items.inc")

