
#ifndef READ_RDI_SEXP_H
#define READ_RDI_SEXP_H

#define R_NO_REMAP
#include <R.h>
#include <Rinternals.h>
#include "read-rdi-common.h"

SEXP rdi_header_list(rdi_header_t* header, uint16_t* data_offset) {
    const char* header_names[] = {"bytes_per_ensemble", "n_data_types", "data_offset", ""};
    SEXP r_header = PROTECT(Rf_mkNamed(VECSXP, header_names));
    SET_VECTOR_ELT(r_header, 0, Rf_ScalarInteger(header->bytes_per_ensemble));
    SET_VECTOR_ELT(r_header, 1, Rf_ScalarInteger(header->n_data_types));

    // wrap in list() so that this can be a data.frame
    SEXP r_data_offset_list = PROTECT(Rf_allocVector(VECSXP, 1));
    SEXP r_data_offset = PROTECT(Rf_allocVector(INTSXP, header->n_data_types));
    for (uint16_t i = 0; i < header->n_data_types; i++) {
        INTEGER(r_data_offset)[i] = data_offset[i];
    }

    SET_VECTOR_ELT(r_data_offset_list, 0, r_data_offset);
    SET_VECTOR_ELT(r_header, 2, r_data_offset_list);
    UNPROTECT(2);

    UNPROTECT(1);
    return r_header;
}

SEXP rdi_unknown_list(uint16_t magic_number) {
    const char* names[] = {"magic_number", ""};
    SEXP df = PROTECT(Rf_mkNamed(VECSXP, names));
    SET_VECTOR_ELT(df, 0, Rf_ScalarInteger(magic_number));
    UNPROTECT(1);
    return df;
}

// start generated by data-raw/read-rdi-tools.R

SEXP rdi_fixed_leader_data_list(rdi_fixed_leader_data_t* fixed) {
    const char* fixed_df_names[] = { "magic_number", "firmware_version", "system_config", "real_sim_flag", "lag_length", "n_beams", "n_cells", "pings_per_ensemble", "cell_size", "blank_after_transmit", "profiling_mode", "low_corr_thresh", "n_code_reps", "pct_gd_min", "error_velocity_maximum", "tpp_minutes", "tpp_seconds", "tpp_hundredths", "coord_transform", "heading_alignment", "heading_bias", "sensor_source", "sensors_available", "bin1_distance", "transmit_pulse_length", "wp_ref_layer_average", "false_target_threshold", "transmit_lag_distance", "cpu_board_serial_number", "system_bandwidth", "system_power", "serial_number", "beam_angle"  , ""};
    SEXP fixed_df = PROTECT(Rf_mkNamed(VECSXP, fixed_df_names));
    SET_VECTOR_ELT(fixed_df, 0, Rf_allocVector(INTSXP, 1));
    SET_VECTOR_ELT(fixed_df, 1, Rf_allocVector(VECSXP, 1));
    SET_VECTOR_ELT(fixed_df, 2, Rf_allocVector(VECSXP, 1));
    SET_VECTOR_ELT(fixed_df, 3, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 4, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 5, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 6, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 7, Rf_allocVector(INTSXP, 1));
    SET_VECTOR_ELT(fixed_df, 8, Rf_allocVector(REALSXP, 1));
    SET_VECTOR_ELT(fixed_df, 9, Rf_allocVector(REALSXP, 1));
    SET_VECTOR_ELT(fixed_df, 10, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 11, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 12, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 13, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 14, Rf_allocVector(INTSXP, 1));
    SET_VECTOR_ELT(fixed_df, 15, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 16, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 17, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 18, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 19, Rf_allocVector(REALSXP, 1));
    SET_VECTOR_ELT(fixed_df, 20, Rf_allocVector(REALSXP, 1));
    SET_VECTOR_ELT(fixed_df, 21, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 22, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 23, Rf_allocVector(REALSXP, 1));
    SET_VECTOR_ELT(fixed_df, 24, Rf_allocVector(REALSXP, 1));
    SET_VECTOR_ELT(fixed_df, 25, Rf_allocVector(INTSXP, 1));
    SET_VECTOR_ELT(fixed_df, 26, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 27, Rf_allocVector(INTSXP, 1));
    SET_VECTOR_ELT(fixed_df, 28, Rf_allocVector(VECSXP, 1));
    SET_VECTOR_ELT(fixed_df, 29, Rf_allocVector(INTSXP, 1));
    SET_VECTOR_ELT(fixed_df, 30, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(fixed_df, 31, Rf_allocVector(VECSXP, 1));
    SET_VECTOR_ELT(fixed_df, 32, Rf_allocVector(RAWSXP, 1));

    INTEGER(VECTOR_ELT(fixed_df, 0))[0] = fixed->magic_number;
    SEXP r_firmware_version = PROTECT(Rf_allocVector(INTSXP, 2));
    for (int j = 0; j < 2; j++) {
        INTEGER(r_firmware_version)[j] = fixed->firmware_version[j];
    }
    SET_VECTOR_ELT(VECTOR_ELT(fixed_df, 1),  0, r_firmware_version);
    UNPROTECT(1);
    SEXP r_system_config = PROTECT(Rf_allocVector(INTSXP, 2));
    for (int j = 0; j < 2; j++) {
        INTEGER(r_system_config)[j] = fixed->system_config[j];
    }
    SET_VECTOR_ELT(VECTOR_ELT(fixed_df, 2),  0, r_system_config);
    UNPROTECT(1);
    RAW(VECTOR_ELT(fixed_df, 3))[0] = fixed->real_sim_flag;
    RAW(VECTOR_ELT(fixed_df, 4))[0] = fixed->lag_length;
    RAW(VECTOR_ELT(fixed_df, 5))[0] = fixed->n_beams;
    RAW(VECTOR_ELT(fixed_df, 6))[0] = fixed->n_cells;
    INTEGER(VECTOR_ELT(fixed_df, 7))[0] = fixed->pings_per_ensemble;
    REAL(VECTOR_ELT(fixed_df, 8))[0] = fixed->cell_size / 100.0;
    REAL(VECTOR_ELT(fixed_df, 9))[0] = fixed->blank_after_transmit / 100.0;
    RAW(VECTOR_ELT(fixed_df, 10))[0] = fixed->profiling_mode;
    RAW(VECTOR_ELT(fixed_df, 11))[0] = fixed->low_corr_thresh;
    RAW(VECTOR_ELT(fixed_df, 12))[0] = fixed->n_code_reps;
    RAW(VECTOR_ELT(fixed_df, 13))[0] = fixed->pct_gd_min;
    INTEGER(VECTOR_ELT(fixed_df, 14))[0] = fixed->error_velocity_maximum;
    RAW(VECTOR_ELT(fixed_df, 15))[0] = fixed->tpp_minutes;
    RAW(VECTOR_ELT(fixed_df, 16))[0] = fixed->tpp_seconds;
    RAW(VECTOR_ELT(fixed_df, 17))[0] = fixed->tpp_hundredths;
    RAW(VECTOR_ELT(fixed_df, 18))[0] = fixed->coord_transform;
    REAL(VECTOR_ELT(fixed_df, 19))[0] = fixed->heading_alignment / 100.0;
    REAL(VECTOR_ELT(fixed_df, 20))[0] = fixed->heading_bias / 100.0;
    RAW(VECTOR_ELT(fixed_df, 21))[0] = fixed->sensor_source;
    RAW(VECTOR_ELT(fixed_df, 22))[0] = fixed->sensors_available;
    REAL(VECTOR_ELT(fixed_df, 23))[0] = fixed->bin1_distance / 100.0;
    REAL(VECTOR_ELT(fixed_df, 24))[0] = fixed->transmit_pulse_length / 100.0;
    INTEGER(VECTOR_ELT(fixed_df, 25))[0] = fixed->wp_ref_layer_average;
    RAW(VECTOR_ELT(fixed_df, 26))[0] = fixed->false_target_threshold;
    INTEGER(VECTOR_ELT(fixed_df, 27))[0] = fixed->transmit_lag_distance;
    SEXP r_cpu_board_serial_number = PROTECT(Rf_allocVector(INTSXP, 8));
    for (int j = 0; j < 8; j++) {
        INTEGER(r_cpu_board_serial_number)[j] = fixed->cpu_board_serial_number[j];
    }
    SET_VECTOR_ELT(VECTOR_ELT(fixed_df, 28),  0, r_cpu_board_serial_number);
    UNPROTECT(1);
    INTEGER(VECTOR_ELT(fixed_df, 29))[0] = fixed->system_bandwidth;
    RAW(VECTOR_ELT(fixed_df, 30))[0] = fixed->system_power;
    SEXP r_serial_number = PROTECT(Rf_allocVector(INTSXP, 4));
    for (int j = 0; j < 4; j++) {
        INTEGER(r_serial_number)[j] = fixed->serial_number[j];
    }
    SET_VECTOR_ELT(VECTOR_ELT(fixed_df, 31),  0, r_serial_number);
    UNPROTECT(1);
    RAW(VECTOR_ELT(fixed_df, 32))[0] = fixed->beam_angle;

    UNPROTECT(1);
    return fixed_df;
}

SEXP rdi_variable_leader_data_list(rdi_variable_leader_data_t* variable) {
    const char* variable_df_names[] = { "magic_number", "ensemble_number", "real_time_clock", "ensemble_number_msb", "bit_result", "sound_speed", "transducer_depth", "heading", "pitch", "roll", "salinity", "temperature", "heading_std", "pitch_std", "roll_std", "transmit_current", "transmit_voltage", "ambient_temperature", "pressure_plus", "pressure_minus", "attitude_temp", "attitude", "contamination_sensor", "pressure", "pressure_std"  , ""};
    SEXP variable_df = PROTECT(Rf_mkNamed(VECSXP, variable_df_names));
    SET_VECTOR_ELT(variable_df, 0, Rf_allocVector(INTSXP, 1));
    SET_VECTOR_ELT(variable_df, 1, Rf_allocVector(INTSXP, 1));
    SET_VECTOR_ELT(variable_df, 2, Rf_allocVector(VECSXP, 1));
    SET_VECTOR_ELT(variable_df, 3, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(variable_df, 4, Rf_allocVector(INTSXP, 1));
    SET_VECTOR_ELT(variable_df, 5, Rf_allocVector(INTSXP, 1));
    SET_VECTOR_ELT(variable_df, 6, Rf_allocVector(INTSXP, 1));
    SET_VECTOR_ELT(variable_df, 7, Rf_allocVector(REALSXP, 1));
    SET_VECTOR_ELT(variable_df, 8, Rf_allocVector(REALSXP, 1));
    SET_VECTOR_ELT(variable_df, 9, Rf_allocVector(REALSXP, 1));
    SET_VECTOR_ELT(variable_df, 10, Rf_allocVector(INTSXP, 1));
    SET_VECTOR_ELT(variable_df, 11, Rf_allocVector(REALSXP, 1));
    SET_VECTOR_ELT(variable_df, 12, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(variable_df, 13, Rf_allocVector(REALSXP, 1));
    SET_VECTOR_ELT(variable_df, 14, Rf_allocVector(REALSXP, 1));
    SET_VECTOR_ELT(variable_df, 15, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(variable_df, 16, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(variable_df, 17, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(variable_df, 18, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(variable_df, 19, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(variable_df, 20, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(variable_df, 21, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(variable_df, 22, Rf_allocVector(RAWSXP, 1));
    SET_VECTOR_ELT(variable_df, 23, Rf_allocVector(VECSXP, 1));
    SET_VECTOR_ELT(variable_df, 24, Rf_allocVector(VECSXP, 1));

    INTEGER(VECTOR_ELT(variable_df, 0))[0] = variable->magic_number;
    INTEGER(VECTOR_ELT(variable_df, 1))[0] = variable->ensemble_number;
    SEXP r_real_time_clock = PROTECT(Rf_allocVector(INTSXP, 7));
    for (int j = 0; j < 7; j++) {
        INTEGER(r_real_time_clock)[j] = variable->real_time_clock[j];
    }
    SET_VECTOR_ELT(VECTOR_ELT(variable_df, 2),  0, r_real_time_clock);
    UNPROTECT(1);
    RAW(VECTOR_ELT(variable_df, 3))[0] = variable->ensemble_number_msb;
    INTEGER(VECTOR_ELT(variable_df, 4))[0] = variable->bit_result;
    INTEGER(VECTOR_ELT(variable_df, 5))[0] = variable->sound_speed;
    INTEGER(VECTOR_ELT(variable_df, 6))[0] = variable->transducer_depth;
    REAL(VECTOR_ELT(variable_df, 7))[0] = variable->heading / 100.0;
    REAL(VECTOR_ELT(variable_df, 8))[0] = variable->pitch / 100.0;
    REAL(VECTOR_ELT(variable_df, 9))[0] = variable->roll / 100.0;
    INTEGER(VECTOR_ELT(variable_df, 10))[0] = variable->salinity;
    REAL(VECTOR_ELT(variable_df, 11))[0] = variable->temperature / 100.0;
    RAW(VECTOR_ELT(variable_df, 12))[0] = variable->heading_std;
    REAL(VECTOR_ELT(variable_df, 13))[0] = variable->pitch_std / 10.0;
    REAL(VECTOR_ELT(variable_df, 14))[0] = variable->roll_std / 10.0;
    RAW(VECTOR_ELT(variable_df, 15))[0] = variable->transmit_current;
    RAW(VECTOR_ELT(variable_df, 16))[0] = variable->transmit_voltage;
    RAW(VECTOR_ELT(variable_df, 17))[0] = variable->ambient_temperature;
    RAW(VECTOR_ELT(variable_df, 18))[0] = variable->pressure_plus;
    RAW(VECTOR_ELT(variable_df, 19))[0] = variable->pressure_minus;
    RAW(VECTOR_ELT(variable_df, 20))[0] = variable->attitude_temp;
    RAW(VECTOR_ELT(variable_df, 21))[0] = variable->attitude;
    RAW(VECTOR_ELT(variable_df, 22))[0] = variable->contamination_sensor;
    SEXP r_pressure = PROTECT(Rf_allocVector(INTSXP, 4));
    for (int j = 0; j < 4; j++) {
        INTEGER(r_pressure)[j] = variable->pressure[j];
    }
    SET_VECTOR_ELT(VECTOR_ELT(variable_df, 23),  0, r_pressure);
    UNPROTECT(1);
    SEXP r_pressure_std = PROTECT(Rf_allocVector(INTSXP, 4));
    for (int j = 0; j < 4; j++) {
        INTEGER(r_pressure_std)[j] = variable->pressure_std[j];
    }
    SET_VECTOR_ELT(VECTOR_ELT(variable_df, 24),  0, r_pressure_std);
    UNPROTECT(1);

    UNPROTECT(1);
    return variable_df;
}

SEXP rdi_bottom_track_list(rdi_bottom_track_t* bottom_track) {
    const char* bottom_track_df_names[] = { "magic_number", "range_lsb", "bottom_track_velocity", "bc", "ba", "bg", "range_msb"  , ""};
    SEXP bottom_track_df = PROTECT(Rf_mkNamed(VECSXP, bottom_track_df_names));
    SET_VECTOR_ELT(bottom_track_df, 0, Rf_allocVector(INTSXP, 1));
    SET_VECTOR_ELT(bottom_track_df, 1, Rf_allocVector(VECSXP, 1));
    SET_VECTOR_ELT(bottom_track_df, 2, Rf_allocVector(VECSXP, 1));
    SET_VECTOR_ELT(bottom_track_df, 3, Rf_allocVector(VECSXP, 1));
    SET_VECTOR_ELT(bottom_track_df, 4, Rf_allocVector(VECSXP, 1));
    SET_VECTOR_ELT(bottom_track_df, 5, Rf_allocVector(VECSXP, 1));
    SET_VECTOR_ELT(bottom_track_df, 6, Rf_allocVector(VECSXP, 1));

    INTEGER(VECTOR_ELT(bottom_track_df, 0))[0] = bottom_track->magic_number;
    SEXP r_range_lsb = PROTECT(Rf_allocVector(INTSXP, 4));
    for (int j = 0; j < 4; j++) {
        INTEGER(r_range_lsb)[j] = bottom_track->range_lsb[j];
    }
    SET_VECTOR_ELT(VECTOR_ELT(bottom_track_df, 1),  0, r_range_lsb);
    UNPROTECT(1);
    SEXP r_bottom_track_velocity = PROTECT(Rf_allocVector(INTSXP, 4));
    for (int j = 0; j < 4; j++) {
        INTEGER(r_bottom_track_velocity)[j] = bottom_track->bottom_track_velocity[j];
    }
    SET_VECTOR_ELT(VECTOR_ELT(bottom_track_df, 2),  0, r_bottom_track_velocity);
    UNPROTECT(1);
    SEXP r_bc = PROTECT(Rf_allocVector(INTSXP, 4));
    for (int j = 0; j < 4; j++) {
        INTEGER(r_bc)[j] = bottom_track->bc[j];
    }
    SET_VECTOR_ELT(VECTOR_ELT(bottom_track_df, 3),  0, r_bc);
    UNPROTECT(1);
    SEXP r_ba = PROTECT(Rf_allocVector(INTSXP, 4));
    for (int j = 0; j < 4; j++) {
        INTEGER(r_ba)[j] = bottom_track->ba[j];
    }
    SET_VECTOR_ELT(VECTOR_ELT(bottom_track_df, 4),  0, r_ba);
    UNPROTECT(1);
    SEXP r_bg = PROTECT(Rf_allocVector(INTSXP, 4));
    for (int j = 0; j < 4; j++) {
        INTEGER(r_bg)[j] = bottom_track->bg[j];
    }
    SET_VECTOR_ELT(VECTOR_ELT(bottom_track_df, 5),  0, r_bg);
    UNPROTECT(1);
    SEXP r_range_msb = PROTECT(Rf_allocVector(INTSXP, 4));
    for (int j = 0; j < 4; j++) {
        INTEGER(r_range_msb)[j] = bottom_track->range_msb[j];
    }
    SET_VECTOR_ELT(VECTOR_ELT(bottom_track_df, 6),  0, r_range_msb);
    UNPROTECT(1);

    UNPROTECT(1);
    return bottom_track_df;
}

// end generated by data-raw/read-rdi-tools.R

#endif
